services:
  front:
    container_name: front
    build: 
      context: ./raphael
    ports:
      - "80:3000"
    depends_on:
      - back
  back:
    container_name: back
    build: 
      context: ./backend
    ports:
      - "8000:8000"
